### ISSUE TITLE
Error: EACCES: permission denied, copyfile 

### ISSUE THREAD

**Issue by nodecentral** [node-red/node-red-docker#221]
### What are the steps to reproduce?

I followed the guide here -> https://nodered.org/docs/getting-started/docker

### What happens?

I get the following errors when it starts,
````

Error: EACCES: permission denied, copyfile '/usr/src/node-red/node_modules/node-red/settings.js' -> '/data/settings.js'                                                                                      
    at Object.copyFileSync (fs.js:1728:3)                                                                                                                                                                    
    at copyFile (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:68:8)                                                                                                                    
    at onFile (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:53:25)                                                                                                                     
    at getStats (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)                                                                                                                   
    at startCopy (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)                                                                                                                  
    at handleFilterAndCopy (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)                                                                                                        
    at Object.copySync (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)                                                                                                            
    at Object.<anonymous> (/usr/src/node-red/node_modules/node-red/red.js:125:20)                                                                                                                            
    at Module._compile (internal/modules/cjs/loader.js:778:30)                                                                                                                                               
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)                                                                                                                                 
npm ERR! code ELIFECYCLE                                                                                                                                                                                     
npm ERR! errno 1                                                                                                                                                                                             
npm ERR! node-red-docker@1.2.9 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`                                                                                           
npm ERR! Exit status 1                                                                                                                                                                                       
npm ERR!                                                                                                                                                                                                     
npm ERR! Failed at the node-red-docker@1.2.9 start script.                                                                                                                                                   
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                                                  
````
### What do you expect to happen?

I expected it to start up and write the required files to the host provided location 
{ "/share/Container/node-red-data/": { "bind": "/data", "rw": true } 

### Please tell us about your environment:

[ ] Platform/OS: QNAP 

[ ] Browser:
 
````

I’ve tried to add a variety of user and group ids to see if that addresses the issues, e.g PUID=0", "PGID=0 but I still get the error

**Comment by hardillb** [comment]
PUID/PGID are **not** a standard way to set process UID/GID for docker containers, they are an artefact of some containers provided by linuxserver.io **only**

The problem is that `/share/Container/node-red-data` is not writable to the user with the UID 1000 (The node-red user as defined in the container)

If you want to change the the UID that the Node-RED process will run under you need to use the docker `-u` command line argument https://docs.docker.com/engine/reference/run/#user

**Comment by nodecentral** [comment]
Thanks @hardillb 

Sorry for not being clearer,  I only added the UID and GID options because I was getting the permission denied error my post is about, I thought that my be related .


Other than that, I’ve followed the Docker instruction here (https://nodered.org/docs/getting-started/docker ) which gives me this error.

**Comment by hardillb** [comment]
No idea, that will be down to the platform you are running it on which I assume is a QNAP NAS.

**Comment by nodecentral** [comment]
Thanks, using the following command looks like it did the job
````
chown 1000 share/Container/node-red-data/
````

**Comment by EduardWitteveen** [comment]
Also had this problem on my synology, gave chmod 777 on the docker/node-red/data directory after which everything seemed to work

**Comment by arseny-sandaar** [comment]
Hello,

I have the same problem, but I didn't get what you had done to solve the problem. May I ask you to provide more practical steps please (because I am quite new here) :)?

Background:
I deployed node-red container aka "IoT edge device module" (nodered/node-red:latest) on an Azure IoT edge device installed on Linux VM on Windows device ([EFLOW](https://learn.microsoft.com/en-us/azure/iot-edge/quickstart?view=iotedge-2018-06)) based on my experience doing it according to [node-red deployment on IoT edge device on Raspberry Pi](https://github.com/iotblackbelt/noderededgemodule).

Unfortunately, **I face the same problem with the same error logs** (I also described the problem [here](https://discourse.nodered.org/t/node-red-does-not-run-on-iot-edge-module-on-a-windows-device/70641), though no decent help) where I thought the problem might have been in the "Binds". 

Furthermore, as node-red docker is for specific architectures (amd64, arm32v6, arm32v7, arm64v8 and s390x), I also thought I have problems due my system which is:
```
Virtualization: microsoft
Operating System: CBL-Mariner/Linux
Kernel: Linux 5.15.67.1-4.cm2
Architecture: x86-64
Hardware Vendor: Microsoft Corporation
Hardware Model: Virtual Machine
```

**Comment by hardillb** [comment]
@arseny-sandaar answered on Stack Overflow here https://stackoverflow.com/questions/74487200/can-i-run-node-red-under-docker-on-vm-eflow-azure-iot-edge-on-windows-device/74488060#74488060

**Comment by rockyessel** [comment]
Im using MacPro
and i don't know what all this means, im trying to install a @sanity.cli package and it is not working.


```
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/@sanity
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@sanity'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@sanity'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/@sanity'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
```

**Comment by hardillb** [comment]
@rockyessel without a lot more context it will be impossible to help you. 

And rather than using a long closed issue, please post to the Node-RED forum or slack (both linked to from the Node-RED homepage) where the larger community can help you, not just the core development team.

When you post include a LOT more detail e.g.

- What version of everything you are using
- Where you are running everything
- How you are trying to install that module (which doesn't appear to be a Node-RED node)? 
- What command lead to that message?

**Comment by girish-khadse** [comment]
Hi.. 
I was facing same issue and managed to fix it using the information in wiki article and comments in this thread. But I still have some doubts. 

I have setup NodeRed on AWS on my test environment. 
Below are my architecture details : 
1. I am using ECS fargate to host the docker image. 
2. I have configured the persistent storage using EFS.
3. Dockerfile consists this : 
           FROM nodered/node-red:latest
4. Deployment is done through Azure Devops pipeline using Terraform scripts.

I was facing some issues with permissions while implementing persistent storage on EFS, which I fixed by using following wiki article : 
https://github.com/node-red/node-red-docker/wiki/Permissions-and-Persistence

Though I could manage setup persistence storage, I still have some doubts : 
When I ran the following command :
        ls -nal /home/ubuntu/node-red
   Expected output was : 
```
      drwxrwxr-x 3 1000  100 4096 Oct  2 12:02 .
      drwxrwxr-x 3 1000  100 4096 Oct  2 09:25 ..
     drwxr-xr-x 3 1000 1000 4096 Oct  2 10:23 data
```

But what I get is : 

```
   drwxr-xr-x 3 0 0 18 Dec 12 04:47 .
  drwxr-xr-x 3 0 0 22 Dec 12 04:47 ..
  drwxr-xr-x 2 0 0  6 Dec 12 04:47 data
```
Also : when I check root user using "id $USER"
instead of getting root user as 1000, I get -> uid=0(root) gid=0(root) groups=0(root)

So I fixed it by doing following : 
I changed my aws task definition to use the user option to override the default userid to '0'. It looks like below now : 

```
     "name": "nodered-image",
    "image": "${container_image}",
    "user": "0:0",
    "restart": "always",
    "essential": true,
```
So can someone help me understand following things : 
1. Why I am getting root user as 0 instead of 1000 ? 
2. Is overriding using  "user": "0:0" is right way to fix the issue? or is their any other better way ?
3. I am using latest image to create container. Is it a right way or should I be using specific stable version instead?

**Comment by rajojon23** [comment]
For anyone still having the issue, I found a solution that's working for me. Just throwing this out there: 

`sudo chown -R $USER:$USER  path/to/your/node-red/data
sudo chmod -R 777  path/to/your/node-red/data

docker run -it --name mynodered -p 1880:1880 -v path/to/your/node-red/data:/data nodered/node-red`

**Comment by jocefello** [comment]
> For anyone still having the issue, I found a solution that's working for me. Just throwing this out there:
> 
> ```
> sudo chown -R $USER:$USER  path/to/your/node-red/data
> sudo chmod -R 777  path/to/your/node-red/data
> docker run -it --name mynodered -p 1880:1880 -v path/to/your/node-red/data:/data nodered/node-red
> ```

Thanks men!!
